### ISSUE TITLE
Feature Request: Notification Sound

### ISSUE THREAD

**Issue by DovydasTEDS** [Henry-Santa/Jerry-Sniper#1]
Add a sound that plays when there is a new flip.

**Comment by Henry-Santa** [comment]
I will be right on this 😀

**Comment by DovydasTEDS** [comment]
Great. You are quite speedy!

**Comment by naromori** [comment]
Any update 'bout the website?

**Comment by Henry-Santa** [comment]
I just fixed it. my bad on not doing it in February I just got really busy. Anyway it works now but the only issue is that u have to interact with the website by clicking at least once before the api even allows sound to be played.
